# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Release NuGet

on:
  release:
    types: [ "published" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/Heap.sln 
    - name: Build
      run: dotnet build --no-restore --configuration release ./src/Heap.sln
    - name: Pack
      run: dotnet pack --no-build --output pkgs -p:PackageVersion=${{ github.event.release.tag_name }} ./src/Heap.sln
    - name: Upload
      run: dotnet nuget push pkgs/*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json